# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AKSwiftSlideMenu' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  react_native_path = "../node_modules/react-native"
  pod "Yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]

  # Pods for AKSwiftSlideMenu

end
